### ISSUE TITLE
Duplicate Symbols (Build Failure)

### ISSUE THREAD

**Issue by ilzxc** [CNMAT/CNMAT-odot#372]
On build, getting one error when linking `o.schedule`:

```
duplicate symbol _messages in:
    /Users/ilyarostovtsev/Documents/code/cnmat/CNMAT-odot/src/build/odot.build/Release/o.schedule.build/Objects-normal/x86_64/o.schedule.o
    /Users/ilyarostovtsev/Documents/code/cnmat/CNMAT-odot/src/build/odot.build/Release/o.schedule.build/Objects-normal/x86_64/pqops.o
duplicate symbol _tmp in:
    /Users/ilyarostovtsev/Documents/code/cnmat/CNMAT-odot/src/build/odot.build/Release/o.schedule.build/Objects-normal/x86_64/o.schedule.o
    /Users/ilyarostovtsev/Documents/code/cnmat/CNMAT-odot/src/build/odot.build/Release/o.schedule.build/Objects-normal/x86_64/pqops.o
ld: 2 duplicate symbols for architecture x86_64
Command MasterObjectLink failed with a nonzero exit code
```

I do not recall having `pqops` back when I was on the project, so any clarity regarding this would be most appreciated.

I'm on 10.13.6 and trying to compile using Xcode 10.0 (freshly updated).

**Comment by ramagottfried** [comment]
hmm, weird -- builds fine here.. you need pqops, it should already be in the xcode project -- linked to the file in the o.schedule folder.

**Comment by ramagottfried** [comment]
fwiw I'm on xcode 9.4.1

**Comment by ilzxc** [comment]
They're both in the project, and the issue is that both contain `_messages` and `_tmp` symbols that the linker can't resolve. Doesn't matter if I build from `make` or from Xcode. I'm relatively sure that one of them is unnecessary for a target (which may have been lost when migrating the project to new Xcode). Is it the case that `pqops` is used in pd external but not in the Max one?

**Comment by ramagottfried** [comment]
strange -- yeah, sounds like Xcode 10 might have screwed up your project.
pqops is used by Max also.

seems like xcode is doubly linking on your system for some reason.

**Comment by ilzxc** [comment]
The issue is definitely in the codebase, since you're including `pqops.h` in `o.schedule` AND it's also included by the `pqops.c` and since the header declares `messages` and `tmp` it seems very odd to me that this ever compiled without some cleverness. I just moved the declarations to be global in `pqops.c` from the header and odot is compiling correctly.

I guess if an update to Xcode 10 breaks your builds, let me know if I can be of any help, because I think I got everything (max & pd) to build properly.

**Comment by ramagottfried** [comment]
oh wow, yeah bizzaro, pqops.h doesn't have a double include `#ifdef` or `#pramga once`, I'm surprised that ever worked!

**Comment by ramagottfried** [comment]
maybe something in clang changed that's being less permissive... 
but anyway, yes, that seems like a bug.

**Comment by ilzxc** [comment]
I’m happy to submit a pull request if needed as I have no way of testing this on an older OS X. Alternatively, we can just close this if you don’t mind submitting a fix for this whenever it becomes necessary. 

Hope all is well and best wishes!

**Comment by ramagottfried** [comment]
thanks ilya! best wishes to you too!

I just pushed what should be a fix for the pqops double include issue, added an `#ifdef` check, and also moved the globals to the .c file for good measure.

as for the Carbon issue, I guess let's wait for a while, as I'm nervous about Xcode 9/10 compatibility. And I'd rather not merge the two until it's really necessary.

If you want to create a pull request that could be useful in the future to have your fixes on record. 

cheers!
